services:
  django:
    build: .
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    ports:
      - "8080:8000"
    volumes:
      - ./aligner:/app/aligner:z
      - ./webapp:/app/webapp:z
      - ./results:/app/results:z
    command: ["sh", "-c", "python manage.py migrate && python manage.py runserver --noreload 0.0.0.0:8000"]
