# Generated by Django 6.0.3 on 2026-04-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionJob',
            fields=[
                ('job_id', models.UUIDField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=255)),
                ('article_filename', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=16)),
                ('output_path', models.CharField(blank=True, max_length=512)),
                ('pockets_json', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
